apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-reservation-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-reservation-api
  template:
    metadata:
      labels:
        app: event-reservation-api
    spec:
      containers:
        - name: event-reservation-api
          image: inesskal/event-reservation-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/event_reservation_db
            - name: SPRING_DATASOURCE_USERNAME
              value: event_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: event_pass
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
